POST http://localhost:3001/api/categ 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Inp6eiIsImlkIjoiNWU4ZjYzMDNmZDQzNDEwNmNiZTljZDdmIiwiaWF0IjoxNTg2NDU5MTYzfQ.jXtwky1jU6qEiF_GWKa9R_70d1dDSB46gcvrzsimNVs

{
    "mainCateg": "main",
    "subCateg": "sub",
    "name": "name",
    "description": "desc"
}